[versions]
kotlin = "2.3.20-Beta2"
kotlinx-io = "0.8.2"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
librarian = { id = "com.gradleup.librarian", version = "0.2.2-SNAPSHOT" }

[libraries]
kotlinx-io-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk9 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-jdk9", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
klibnanolog = "org.jraf.klibnanolog:klibnanolog:1.0.1"
klibopenai = "org.jraf.klibopenai:klibopenai:1.0.0"
